### PR TITLE
Adds wemake-python-styleguide

### PR DESCRIPTION
**Pull request by sobolevn**
Project: https://github.com/wemake-services/wemake-python-styleguide
pyproject.toml: https://github.com/wemake-services/wemake-python-styleguide/blob/master/pyproject.toml
Docs: https://wemake-python-stylegui.de/en/latest/

- [x] I have read and understood the [Contribution Guidelines](https://github.com/carlosperate/awesome-pyproject/blob/master/contributing.md)
- [x] I am making an individual pull request for each suggestion
- [x] I have added a useful title to the commit. 
- [x] I have added a useful title to this PR.
- [x] I have added the new entry to the bottom of its the category
- [x] I have used the following format:

### CODE REVIEW

**Comment by carlosperate** [comment]
Thank you for the contribution @sobolevn!

While the project itself uses pyproject.toml for their development, looking at [configuration documentation](https://wemake-python-stylegui.de/en/latest/pages/usage/configuration.html) it looks like users of this linter still need to use a `setup.cfg` file.
Is there a way to configure wemake-python-styleguide with a pyproject.toml file?

**Comment by sobolevn** [comment]
Yes, with the use of `flakehell` which was created in close connection with `wemake-python-styleguide`

**Comment by carlosperate** [comment]
Oh great! In that case could you change the URL to anywhere in the documentation that might indicate that?

**Comment by sobolevn** [comment]
Here: https://wemake-python-stylegui.de/en/latest/pages/usage/integrations/flakehell.html

**Comment by carlosperate** [comment]
Great, I've updated the link and it's ready to merge. Thanks @sobolevn!

**Pull request merged**
