### PR TITLE
Add Flake9

### LINKED ISSUE #23: Add Flake9
I have created [Flake9](https://gitlab.com/retnikt/flake9), a fork of [Flake8](https://gitlab.com/PyCQA/flake8) (who [refused](https://gitlab.com/PyCQA/flake8/-/issues/428) to implement it) that supports reading configuration from `pyproject.toml` files. Is it worth adding here?

### PR DESCRIPTION
**Pull request by retnikt**
Closes #23

### CODE REVIEW

**Comment by retnikt** [comment]
No, there isn't really any documentation on that sorry, it's just the exact same format as Flake8's config.

**Comment by djesic** [comment]
@retnikt I've tried just copying my `.flake8` configuration into `pyproject.toml`, but it's not working.
Here's the config
```
[tool.flake8]
ignore = E203, E266, E501, W503, F403, F401
max-line-length = 120
max-complexity = 25
select = B,C,E,F,W,T4,B9
```
And here is the error I get when running pre-commit 
```
E501 line too long (81 > 79 characters)
```
I'd say that my config isn't parsed.

Also, this breaks my black pre-commit hook with the following error, regardless of where the config is placed within the `pyproject.toml` file

```
pyproject.toml: Error reading configuration file: This float doesn't have a leading digit 
```

Let me know if you want me to make an issue for this on your repo.

**Comment by retnikt** [comment]
In TOML you have to quote your strings. When I said "the same format" above I meant the config variables are the same values. I'll add something to its README to explain.

**Comment by djesic** [comment]
I've tried the snippet you provided and also wrapping them individually in quotes and into an array, the black pre-commit error is gone in either case, but the settings are not used when running. I still get line length error, `max-line-length` isn't taken into account. Also, I get a F401 warning as well even though I've added it to ignore.

Here's the config in my `.pre-commit-config.yaml`, just in case
```
-   repo: https://gitlab.com/retnikt/flake9
    rev: 3.8.3
    hooks:
    - id: flake8
      additional_dependencies: ['flake8-comprehensions', 'flake8-rst-docstrings']
```

**Comment by retnikt** [comment]
@djesic let's move this discussion to an issue in my repo

**Comment by carlosperate** [comment]
I can see that the readme now contains some docs about pyproject.toml, great! All good to merge 👍

**Pull request merged**
