### PR TITLE
Add edgelist-mapper

### PR DESCRIPTION
**Pull request by simonepri**
### Resource description

This a small tool used to build this [collection of datasets](https://github.com/simonepri/datasets-knowledge-embedding).
I think is a relatively good example to showcase how to setup a simple python CI.

### By submitting this pull request I confirm I've read and complied with the below requirements

- [x] I have read and understood the [Contribution Guidelines](https://github.com/carlosperate/awesome-pyproject/blob/master/contributing.md)
- [x] I am making an individual pull request for each suggestion
- [x] I have added a useful title to the commit.
- [x] I have added a useful title to this PR.
- [x] I have added the new entry in alphabetical order
- [x] I have used the following format:
```
- [Resource Title](link) - Resource short Description (2 lines or less in total)
```

### CODE REVIEW

**Comment by carlosperate** [comment]
Hi @simonepri,

Thank you for the contribution. Please do correct me if I'm wrong, this is an app/tool that uses poetry with a pyproject.toml file, rather than a tool that is configured via pyproject.toml, right?
At the moment the list is only for collecting projects that are configured via pyproject.toml, and for examples there is a section for templates. Otherwise it would be really hard to decide which projects to showcase here as "good practice" examples.

**Comment by simonepri** [comment]
What do you mean exactly by "rather than a tool that is configured via pyproject.toml"?

**Comment by carlosperate** [comment]
Oh, okay! Thanks for the clarification @simonepri, I didn't realise the project could be used as well as a library.
So if a user were to install the edgelist-mapper dependency, they would be able to configure it via their pyproject.toml file?
Do you have a link to that in thee documentation? Where possible this list links to the docs that indicate how to use the pyprojec.toml file.

**Comment by simonepri** [comment]
> they would be able to configure it via their pyproject.toml file?
Oh, I think I now see what you meant before. Are you referring to the possibility to specify options in the `pyprojec.toml` file that are then read by the library (i.e. black) to change their behaviour?

I thought this collection was more about projects using the `pyprojec.toml` in general, that's the reason why I opened the PR. If that's not the case I guess we should change the readme a bit to make this more clear (because it wasn't for me).

> I didn't realise the project could be used as well as a library.
Well you can, but it's thought to be used as a CLI.

**Comment by carlosperate** [comment]
I think you are right, I need to make that a bit more clear, I'll add an entry to the PR template to clarify that.

Thank you again for your contribution and apologies for the mix up!

**Pull request closed without merging**
